services:
  db:
    image: mysql:8.0
    container_name: seguro-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: segurointeligente
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
      dockerfile: ./cmd/api/Dockerfile
    container_name: seguro-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: segurointeligente
      # OPENAI_API_KEY: ${OPENAI_API_KEY}
